from enum import Enum


class ActivityAction(str, Enum):
    PRODUCT_CREATE = "PRODUCT_CREATE"
    PRODUCT_UPDATE = "PRODUCT_UPDATE"
    PRODUCT_DELETE = "PRODUCT_DELETE"

    TAG_CREATE = "TAG_CREATE"

    PROFILE_UPDATE = "PROFILE_UPDATE"

    USER_REGISTER = "USER_REGISTER"
    USER_DELETE = "USER_DELETE"

    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_LOGOUT = "AUTH_LOGOUT"


class ActivityEntityType(str, Enum):
    PRODUCT = "PRODUCT"
    TAG = "TAG"
    USER = "USER"
    PROFILE = "PROFILE"
